### ISSUE TITLE
DragNDrop Bereich direkt zur Contao Dateiverwaltung hinzufügen

### ISSUE THREAD

**Issue by backbone87** [menatwork-ia/valumsFileUploader#1]
Wär doch cool, wenn man direkt in der Contao Dateiverwaltung, die Möglichkeit hätte, Dateien zu droppen.
Der DropBereich sollte vielleicht auch erst dann sichtbar werden, wenn man eine Datei grad "festhält".

Dadurch kann man sofort Dateien über mehrere Verzeichnisse verteilen.
Die Upload zusammenfassung, sollte dann vielleicht in einer "virtuellen" rechten Spalte passieren, oder im "Message" Bereich der Dateiverwaltung.

**Comment by andreasisaak** [comment]
http://www.contao-forge.org/issues/1356
