### ISSUE TITLE
Automatisches skalieren von Bildern

### ISSUE THREAD

**Issue by menatwork-dev** [menatwork-ia/valumsFileUploader#14]
Wenn bilder mittels valumsFileUploader hochgeladen werden, sollten diese auf die im BE vorgenommenen Einstellungen (Maximale Bildbreite und Bildhöhe) skaliert werden.

_--- Originally created by Daniel Fred on 24.05.2011 15:53._

**Comment by Joam55** [comment]
Ui, toll für tango-franken.de
LG dtptiger

**Comment by frontendschlampe** [comment]
Echt genialer Uploader. Vielen Dank. Wann denkt Ihr, dass Ihr die Funktion eingebaut habt? ;-)

**Comment by andreasisaak** [comment]
Enthalten in diesem Commit:

f2d929c163267f747dfbc5921b18da392c65624e

**Comment by frontendschlampe** [comment]
Hab es gerade mal getestet und es funktioniert super. Man muss aber die Größe direkt unter persönliche Einstellungen beim Uploader vornehmen?! Die Contao-eigenen Einstellungen werden ignoriert?! Als Erweiterung dieser Funktionalität könnte ich mir einen kurzen Status hinter jedem erfolgreichen Update gut vorstellen: "Ihr Bild wurde auf die max. Maße bla x bla verkleinert!" ... wie beim Standard Uploader. Ansonsten alles schick ... Upload per Drag + Drop sowie per Klick funkt bisher ohne Probleme! Weiter tun ... :-)

**Comment by andreasisaak** [comment]
Wir hatten das ja schon im IRC besprochen, aber an dieser Stelle nochmal für alle interessierten. valumsFileUploader skaliert Bilder beim Upload sobald man die Checkbox in den Einstellungen aktiviert. Bei diesem Vorgang verwendet valums die Contao eigenen Einstellungen.

Sollte man die zwei Felder "Breite/Höhe" noch füllen, dann werden diese als Basis verwendet. So hat man die vollste Kontrolle.

**Comment by Joam55** [comment]
"sobald man die Checkbox in den Einstellungen aktiviert" ...
ich steh auf dem Schlauch, wo finde ich diese Checkboxen?
LG dtptiger

**Comment by andreasisaak** [comment]
Wo bisher auch. In den persönlichen Daten deines Accounts. Da wurde der valumsFileUploader doch auch aktiviert?!

**Comment by Joam55** [comment]
Ok, habe den dort aktiviert, aber die einzige checkbox die ich dem zuordnen kann:
 x Dateien nicht überschreiben

**Comment by andreasisaak** [comment]
Dann hast du nicht wie geschrieben den aktuellsten Stand geladen:

https://github.com/menatwork/valumsFileUploader/zipball/master

**Comment by Joam55** [comment]
Stimmt, hatte nur das Repository verwendet.

**Comment by Joam55** [comment]
Hi Andreas, jetzt :-)
Danke!
