### ISSUE TITLE
Dateiverwaltung Popup

### ISSUE THREAD

**Issue by menatwork-dev** [menatwork-ia/valumsFileUploader#19]
Im Dateiverwaltungs Popup, also das was erscheint, wenn man z.B. bei der Bildauswahl auf das Dateiverwaltungs-Symbol klickt funktioniert der Uploader leider nicht. Ist jetzt kein Beinbruch, aber für eine kommende Version wäre das nicht schlecht.

_--- Originally created by Tristan Lins on 10.04.2011 13:42._

**Comment by Visual-Notes** [comment]
Mit valumsFileUploader 3.1.0 rc2 Build 14 funktioniert es leider immer noch nicht. 

Schade, dass dieses Problem als Feature eingestuft wurde, denn ist es ziemlich eindeutig ein Defekt: die Beschriftung im Popup-Fenster wird doppelt angezeigt, das Drag&Drop-Feld einfach, und der Upload wird als erfolgreich angezeigt, obwohl tatsächlich nichts hochgeladen wurde.
