### ISSUE TITLE
Dateien im Frontend nach dem Upload löschen

### ISSUE THREAD

**Issue by kahl-dev** [menatwork-ia/valumsFileUploader#27]
Man sollte die Möglichkeit bekommen eine Datei vor dem Absenden des Formulars wieder zu löschen.

**Comment by vates** [comment]
Neben einem "entfernen" wäre auch ein Miniaturbild sinnvoll.

Da ich mir das im Frontend für z.B. Kleinanzeigen, Immobilien usw. vorstellen könnte, muss ich da ein wenig Komfort anbieten. Mir schwebt da so etwas vor wie bei eBay-Kleinanzeigen (http://kleinanzeigen.ebay.de/anzeigen/p-anzeige-aufgeben-schritt2.html). Kann man auch testen, ohne ein Inserat aufzugeben. Nur vorher Kategorie auswählen und ein (nichtssagendes) Bild auswählen. Das wird übrigens auch sofort hochgeladen und bleibt dort, wenn man die Aktion abbricht. Hier habe ich eine Vorschau und auch einen "entfernen" - Link

**Comment by kahl-dev** [comment]
@vates Dein Wunsch mit dem Miniaturbild ist ganz nett gehört jedoch in ein neues feature request.
