### ISSUE TITLE
Integration in Catalog

### ISSUE THREAD

**Issue by MacKP** [menatwork-ia/valumsFileUploader#30]
The Catalog Frontend-Edit realy needs something like that ^^
So it would be great, when you integrate this in the catalog.

regards

**Comment by HellPat** [comment]
https://github.com/menatwork/valumsFileUploader/issues/16
 I think it's duplicate. But I'm happy I'm not the only one who would like to see that.
I'd like to have something like this in FE + BE. :-D

For huge catalogs with about 15000 entries where everyone has 5 to 10 images contao-way with the data manager definitely fails :-D

**Comment by MacKP** [comment]
Oh sorry psren, this is realy the same XD
I didn't check the other tickets...
Can be closed (dublicate)

regards
