### ISSUE TITLE
Contao 2.11.0: Läd keine Dateien hoch

### ISSUE THREAD

**Issue by Visual-Notes** [menatwork-ia/valumsFileUploader#31]
Contao 2.11.0
valumsFileUploader 3.1.0 rc2 Build 3
ajax-upload 1.0.0 stable Build 9
ajax 1.1.3 stable Build 7

valumsFileUploader läd auf keiner meiner Contao 2.11.0 Installationen Dateien hoch. 

Es gibt keine Fehlermeldungen. Der Dateiname der hochzuladenden Datei erscheint in roten Lettern. Allerdings keine "...fehlgeschlagen"-Meldung. Debug und Detaillierte Fehlermeldung ist aktiviert, das System-Log weist keinen Eintrag auf.

**Comment by wiesson** [comment]
bei mir auch so.

**Comment by andreasisaak** [comment]
BE oder FE?

**Comment by wiesson** [comment]
BE

**Comment by andreasisaak** [comment]
Dann benötige ich mehr Informationen. So kann ich nicht helfen

**Comment by Visual-Notes** [comment]
Möglicherweise interagiert der Uploader mit einer anderen Erweiterung (wie seinerzeit mit custom_be_modules).
Vielleicht hilft diese Liste installierter Erweiterungen.

ajax    1.1.3 stable
ajax-upload     1.0.0 stable
articles    1.0.1 stable
backboneit_navigation   1.2.0 beta1
BackupDB    1.5.0 stable
boxes   1.14.1 stable
ce_be_remarks   0.3.0 stable
ce_nonverblaster    1.2.1 stable
ce_spacer   1.1.0 stable
cleardefault    2.0.0 rc1 
clearlog    1.1.0 stable
content_cssid_select    1.0.0 rc1
csseditor   2.7.0 beta1
cssExport   1.0.0 beta1
delirius_search_replace     1.0.0 beta1
downloadarchive     1.5.0 stable
easy_themes     1.3.0 stable
efg     1.15.0 stable
html5media  1.0.2 stable
Lightbox4ward   1.4.0 stable
meta_editor     0.2.5 rc2
module_richtext     0.1.0 stable
MultiColumnWizard   2.0.0 stable
newsgallery     1.0.5 stable
nodePicker  1.1.0 stable
secure_accessdata   1.0.0 beta1
subcolumns  1.2.1 stable
tags    1.7.4 stable
tags_news   1.3.0 stable
timetags    0.1.0 stable
valumsFileUploader  3.1.0 rc2
wf_extendedBreadcrumb   2.1.0 stable
xDefaults   1.0.1 stable

**Comment by Visual-Notes** [comment]
Nachtrag zu den Erweiterungen:
Ein Deaktivieren aller installierter Erweiterungen (außer valumsFileUploader natürlich) löst das Problem nicht, welches seit dem Update von 2.10.4 auf 2.11.0 besteht.

**Comment by ghost** [comment]
Bei mir besteht das Problem im Frontend. Zwar lädt er bei Contao 2.11 Dateien hoch (system/tmp), aber nicht dort wo ich will. Ich habe im Formulargenerator ein Zielverzeichnis angegeben, darauf reagiert das Skript leider überhaupt nicht.

Ich habe außerdem dem Formular angewiesen, die Daten in einer Datenbank-Tabelle zu speichern, das funktioniert für den Dateipfad leider auch nicht. Er speichert alles außer das Feld, wo der Multiuploader im Frontend ist.

**Comment by andreasisaak** [comment]
@ProloxxWebdesign 

Bitte melde deinen Fehler in einem neuen Ticket. Das ist ein anderes Problem und hat nichts mit diesem Ticket zu tun. Sobald du dein Ticket angelegt hast, lösche ich deinen Beitrag hier.

Ich möchte die Fehler sauber getrennt haben.

**Comment by Visual-Notes** [comment]
Ich habe nun den valumsFileUploader deinstalliert und neu installiert. Nun erscheint beim Upload die Fehlermeldung "...fehlgeschlagen" in Grün, die Datei bzw. die Dateien sind aber korrekt hochgeladen worden.

Dieser Beitrag hat mich darauf gebracht, dass es sich eigentlich nur um ein kosmetisches Problem handelt:

https://www.contao-community.de/showthread.php?16867-valumsFileUploader-Mehrfachupload-ohne-Flash&p=184963&viewfull=1#post184963

Das von mir im ersten Beitrag dieses Threads beschriebene Verhalten trat kurz nach dem Update auf Contao 2.11.0 auf. Seit Neuinstallation des valumsFileUploaders gibt es beim Hochladen von Dateien die Fehlermeldung "...fehlgeschlagen". 

Ich muss gestehen, dass ich erst heute nachgesehen habe, ob der Datei-Upload tatsächlich fehlgeschlagen ist.

**Comment by kahl-dev** [comment]
@africanforest Es ist schön zu hören das nun der Upload bei dir auch funktioniert. Das kosmetische CSS Problem ist auch bereits behoben und in git gepushed aber noch nicht im regulären ER.

**Comment by andreasisaak** [comment]
Dann mache ich dieses Ticket mal zu weil es schon ein anderes Ticket diesbezüglich gibt.
