### ISSUE TITLE
Fehlermeldung trotz erfolgreicher Übertragung

### ISSUE THREAD

**Issue by wiesson** [menatwork-ia/valumsFileUploader#32]
Sobald der Upload beginnt, wird die Meldung "fehlgeschlagen" ausgegeben. (Unabhängig ob die Datenübertragung erfolgreich war)

Fehlermeldung: ![Beispiel](http://dl.dropbox.com/u/15758091/Bildschirmfoto%202012-02-20%20um%2012.52.44.png)

Nachtrag: Contao 2.11, aktuelle Version aus dem Repository, sonst keine Erweiterung installiert (Außer Ajax & Ajax Upload natürlich)

**Comment by andreasisaak** [comment]
Das ist lediglich ein CSS-Bug. Wird im nächsten Commit behoben sein.

**Comment by andreasisaak** [comment]
Behoben in diesem Commit:

1bb82af5856c1c3cf94762614b9634bd5e7733a4
