### ISSUE TITLE
eigener Pfad im Fomulargenerator wird nicht verarbeitet

### ISSUE THREAD

**Issue by ghost** [menatwork-ia/valumsFileUploader#33]
Bei mir besteht ein Problem im Frontend. Zwar lädt er bei Contao 2.11 Dateien hoch (system/tmp), aber nicht dort wo ich will. Ich habe im Formulargenerator ein Zielverzeichnis angegeben, darauf reagiert das Skript leider überhaupt nicht.

Ich habe außerdem das Formular angewiesen, die Daten in einer Datenbank-Tabelle zu speichern, das funktioniert für den Dateipfad leider auch nicht. Er speichert alles außer das Feld, wo der Multiuploader im Frontend ist.

**Comment by kahl-dev** [comment]
Hallo ProloxxWebdesign,

leider kann ich deinen Fehler nicht reproduzieren. Könntest du mir eine auflisten oder besser noch ein screenshot von den Einstellungen des valumsFileUploaders in der Form Fields geben?

**Comment by ghost** [comment]
Hallo,

hier hast du einen Screenshot. ![Screenshot](http://www.proloxx-webdesign.de/downloads/uploader_config.jpg)

**Comment by kahl-dev** [comment]
Kannst du mir den an meine Firmenadresse schicken?

**Comment by kahl-dev** [comment]
@ProloxxWebdesign 

Die neue Version steht im ER kannst du bitte ein Feedback abgeben, ob es bei dir nun geht, damit ich das Ticket schließen kann.

**Comment by andreasisaak** [comment]
Da es hierzu keine Meldung mehr gibt und ich annehmen muss das sich das Problem erledigt hat, schließe ich das Ticket

**Comment by davidenke** [comment]
Ich habe genau dieses Problem [immernoch](https://community.contao.org/de/showthread.php?16867-valumsFileUploader-Mehrfachupload-ohne-Flash&p=235256&viewfull=1#post235256)...
