### ISSUE TITLE
Dezimal- und Tausender-Trennzeichen vertauscht

### ISSUE THREAD

**Issue by WollZi** [menatwork-ia/valumsFileUploader#35]
In der Datei ValumsFeFileUpload.php ist in der Funktion generate() in der php-Funktion number_format das Komma mit dem Punkt vertauscht. Bei kleinen Dateien fällt es nicht auf.

Zudem wäre es schön, wenn man für kleinere Dateien statt der Größe in MB die Angabe in kB angezeigt bekommt. Nach dem Aktualisieren der Seite steht bei kleineren Dateien dann 0.0MB. Bisher habe ich das mit einer zusätzlichen Funktion gelöst, die ich statt number_format im String $tmpReturn verwende:

``` php
function formatSize($bytes) {
 $fileSize = $bytes/1024;
 if ($fileSize > 999) { // Ausgabe in MB
  return number_format($fileSize / 1024, 1, ',', '.').'MB';
 } else {
  return number_format($fileSize, 1, ',', '.').'kB';
 }
};
```

</section><section>

Vielen Dank, für die tolle Erweiterung (hoffe man darf das hier sagen).

**Comment by andreasisaak** [comment]
Ja man darf das hier sagen ^^
