### ISSUE TITLE
Fatal error: Could not load class UserExt

### ISSUE THREAD

**Issue by balesi** [menatwork-ia/valumsFileUploader#36]
Ich weiß nicht seit wann der Fehler da ist, aber nach dem update auf 2.11 ist er mir aufgefallen.

Ich bekomme nach klick auf Benutzer im BE folgende Fehlermeldung:

Code:

``` php
Fatal error: Could not load class UserExt in /Pfad zur Installation/system/functions.php on line 104

#0 [internal function]: __error(256, 'Could not load ...', '/Pfad zur Installation...', 104, Array)
#1 /Pfad zur Installation/system/functions.php(104): trigger_error('Could not load ...', 256)
#2 /Pfad zur Installation/system/modules/valumsFileUploader/dca/tl_user.php(61): __autoload('UserExt')
#3 /Pfad zur Installation/system/libraries/Controller.php(2737): include('/Pfad zur Installation...')
#4 /Pfad zur Installation/system/modules/backend/Backend.php(189): Controller->loadDataContainer('tl_user')
#5 /Pfad zur Installation/contao/main.php(120): Backend->getBackendModule('user')
#6 /Pfad zur Installation/contao/main.php(230): Main->run()
#7 {main}
```

Wenn ich in den Einstellungen den valumsFileUploader deaktiviere, kann ich die Einstellungen in den Benutzern normal vornehmen, natürlich wird mir der Uploader nicht mehr angeboten.
Der FancyUploader steht auch nicht mehr zur Verfügung.
Aktiviere ich den valumsFileUploader in den Einstellungen wieder, erscheint die Fehlermeldung und ich komme nicht mehr in die Benutzer rein.
Ich habe auch schon den Uploader deinstalliert und wieder installiert, mit und ohne löschen der Files in der Datenbank - ohne Erfolg.

**Comment by kahl-dev** [comment]
@balesi 

Wir haben die Klasse umbenannt. Könntest du bitte einmal die aktuelle Version aus dem Git herunterladen und testen, ob die bei dir jetzt gefunden wird?

**Comment by balesi** [comment]
Leider nein, gleicher Fehler:
Code:

``` php
Fatal error: Could not load class tl_user_vfu in /Pfad zur Installation/system/functions.php on line 104

#0 [internal function]: __error(256, 'Could not load ...', '/Pfad zur Installation...', 104, Array)
#1 /Pfad zur Installation/system/functions.php(104): trigger_error('Could not load ...', 256)
#2 /Pfad zur Installation/system/modules/valumsFileUploader/dca/tl_user.php(61): __autoload('tl_user_vfu')
#3 /Pfad zur Installation/system/libraries/Controller.php(2737): include('/Pfad zur Installation...')
#4 /Pfad zur Installation/system/modules/backend/Backend.php(189): Controller->loadDataContainer('tl_user')
#5 /Pfad zur Installation/contao/main.php(120): Backend->getBackendModule('user')
#6 /Pfad zur Installation/contao/main.php(230): Main->run()
#7 {main}
```

P.S.: ich habe nur die tl_user.php hochgeladen - war das korrekt?

**Comment by andreasisaak** [comment]
Ja das war korrekt. Leider gehen mir jetzt auch die Ideen aus. Wenn wir jetzt noch helfen sollen dann benötigen wir dringend ein Zugang zum System.

Welche PHP Version verwendest du?

**Comment by lindesbs** [comment]
Und : Welche Erweiterungen hast Du installert.

**Comment by balesi** [comment]
PHP habe ich gerade geprüft: 5.3.10

**Comment by andreasisaak** [comment]
Am schnellsten wäre noch eine Auflistung aller Extensions auf dem System. Dann brauche ich vielleicht kein Zugang.

**Comment by balesi** [comment]
ajax    1.1.3 stable    7
ajax-upload 1.0.0 stable    9
avatar  1.0.1 stable    34
backend_user_online 1.2.0 stable    1
calendar_ical   1.3.2 stable    9
cron    1.1.0 stable    18
dlh_googlemaps  1.1.1 stable    5
fblikeit    2.1.0 stable    8
geshi   1.0.8 stable    29
googleanalytics 1.3.4 stable    3
googleplus1 2.0.0 stable    9
helpdesk    1.3.10 stable   21
inputcount  1.4.2 stable    15
MultiColumnWizard   2.0.1 rc2   5
myfavicon   0.1.0 stable    14
newstwitter 1.2.0 stable    15
PiwikTrackingTag    2.1.0 stable    7
registration_info_mailer    2.0.1 stable    8
valumsFileUploader  3.1.0 rc2   8
videobox    1.1.1 stable    8

**Comment by andreasisaak** [comment]
Und wenn du alle Extensions deaktivierst, außer valumsFileUploader kommt es trotzdem zu dem Fehler?

**Comment by balesi** [comment]
ja, dann kommt es ebenfalls zu dem Fehler.

**Comment by andreasisaak** [comment]
Gut. Dann bitte einmal alle notwendigen Zugangsdaten (Backend & FTP) an meine E-Mail-Adresse. Die findest du unter meinem Bild auf dieser Seite verlinkt:

https://github.com/andreasisaak

**Comment by andreasisaak** [comment]
Ich habe bisher nichts mehr erhalten, das Problem hat sich also erledigt?
