### ISSUE TITLE
Falsche Upload-Meldung

### ISSUE THREAD

**Issue by WollZi** [menatwork-ia/valumsFileUploader#37]
Ich habe mal den Uploader (Build 8) im IE (7..10), Opera, Chrome und Mozilla getestet. Alle Uploads waren erfolgreich. Die Meldung waren jedoch unterschiedlich.
Im IE und in Opera erscheint nach dem Upload die Meldung "Fehlgeschlagen". In der Statuszeile vom IE wird der Fehler mit:" '0[...]' ist Null oder kein Objekt" angezeigt. Gemeint ist damit die Zeile 51 im Template form_valums.html5.
Chrome zeight beim Upload den Dateinamen, die Grafik (2 Pfeile), "Abbrechen" und "Fehlgeschlagen" an. Nach dem Upload wird die Datei mit der Größe angezeigt.
In Mozilla funktioniert es.

Beim Einpflegen des Punktes #34 (Danke noch mal dafür) in den Templates be_valums.html5 (Zeile 35) und be_valums.tpl (Zeile 36) ist mir aufgefallen, dass jeweils der Backslash im div-Tag fehlt.

**Comment by andreasisaak** [comment]
> Beim Einpflegen des Punktes #34 (Danke noch mal dafür) in den Templates be_valums.html5 (Zeile 35) und be_valums.tpl (Zeile 36) ist mir aufgefallen, dass jeweils der Backslash im div-Tag fehlt.

Stimmt. Da fehlt die Maskierung für das JS. Das holen wir gleich morgen mal nach.

> Im IE und in Opera erscheint nach dem Upload die Meldung "Fehlgeschlagen". In der Statuszeile vom IE wird der Fehler mit:" '0[...]' ist Null oder kein Objekt" angezeigt. Gemeint ist damit die Zeile 51 im Template form_valums.html5.
> Chrome zeight beim Upload den Dateinamen, die Grafik (2 Pfeile), "Abbrechen" und "Fehlgeschlagen" an. Nach dem Upload wird die Datei mit der Größe angezeigt.

Könnten wir davon eventuell Screenshots bekommen? Grade der IE sollte mit dem letzten Github Commit ruhig gestellt sein. Hast du die aktuellste Github Version in der Verwendung?

**Comment by WollZi** [comment]
Ich habe die Version 3.1.0 rc2 Build 8 installiert und nur die Änderungen #34 und #35 vorgenommen.
Getestet habe ich den Uploader nur offline. Screenshots kann ich gern liefern. Wie kann ich die hochladen? Sorry, arbeite das erste Mal mit github.

**Comment by andreasisaak** [comment]
Nimm bitte erstmal das ganze aktuelle Github Package. Wir haben ja auch noch ein paar Fehler mehr gefixt. Und wenn du Screenshot posten willst, einfach auf Fremdhostern hochladen. Ich nehme immer http://www.imagebanana.com/

Wie du sie einfügen kannst, siehst du wenn du die Taste "m" drückst solange du ein Kommentar schreibst.

**Comment by WollZi** [comment]
Ok, habe die Dateien aktualisiert. Leider keine Veränderung.

Für Chrome sieht es beim Upload so aus:
![Opera](http://img7.imagebanana.com/img/yv4zdooi/opera.jpg)

Für den IE8:
![IE](http://img7.imagebanana.com/img/9n6t6h0h/ie8.jpg)

Nach dem Aktualisren der Seite im IE8:
![IE](http://img7.imagebanana.com/img/8ok73vt9/ie8_1.jpg)

**Comment by andreasisaak** [comment]
Ich klemm mich nochmal hinter. Scheinen reine Browserbugs zu sein, in meinen Tests lief alles recht sauber.

**Comment by WollZi** [comment]
Besten Dank.

**Comment by andreasisaak** [comment]
@patrickkahl 

Leider ist der Fehler IMMER noch nicht behoben.
Mit anderen Browsern mag ich es garnicht erst testen. Bitte gleich am Montag fixen

![Firefox 11](http://img7.imagebanana.com/img/9ysk9apc/failed.jpg)
