### ISSUE TITLE
Inkompatibel mit filepicker4ward

### ISSUE THREAD

**Issue by psi-4ward** [menatwork-ia/valumsFileUploader#40]
Ich nutze in der Erweiterung [filepicker4ward](https://github.com/psi-4ward/filepicker4ward) im Grunde das normale "files"-Modul worin der Uploader eingebunden ist. Allerdings werden Dateien nicht wirklich hochgeladen, trotz eines _success:true_ des ajaxResponders. 

Wäre toll wenn ihr das mal prüfen könntet - die einzige Unstimmigkeit ist der Ort der  _files.php_ die ich von /contao nach /system/modules/filepicker4ward kopiert und etwas angepasst habe.

**Comment by kahl-dev** [comment]
Der Bug wurde <a href="https://github.com/menatwork/valumsFileUploader/issues/19">hier</a> besrochen und behoben

**Comment by psi-4ward** [comment]
Bestätige, funzt perfekt!
Danke
