### ISSUE TITLE
contao 2.11.0 => bilder werden in inhaltselementen nicht hochgeladen

### ISSUE THREAD

**Issue by steff74** [menatwork-ia/valumsFileUploader#42]
ich verwende den valumsFileUploader, welcher in der dateiverwaltung super funktioniert.

leider kann ich das vom upload in inhaltselementen, also zb. nachrichten oder text-elementen, wo bilder direkt hochladen werden sollen, nicht behaupten.
dateien lassen sich zwar auswählen und es sieht auch so aus, als ob valumsFileUploader alles hochlädt, in der dateiverwaltung sind die bilder dann aber nicht vorhanden.

laut sys-log sollte das bild auch hochgeladen sein. ich hab debugging und die fehlermeldungen beim vfu aktiviert - keine ausgabe.

mit dem standard-uploader funktionierts.

ich hab das verhalten auf 3 verschiedenen installationen - ajax, ajax-upload und valumsFileUploader sind aktuell.

**Comment by hasenbaer** [comment]
Möchte die Meldung von steff74 genauso für die Version Contao 2.11.1 bestätigen. Die Datei landet bei mir mit Chrome und Firefox (jew. aktuell) im system/tmp. Im IE8 funkionierts bei mir in Nachrichten, Text-Elementen ... gar nicht.

**Comment by andreasisaak** [comment]
Schon im Ticket #19 gemeldet.
