### ISSUE TITLE
Double-Window inside Pop-up File Manager (new)

### ISSUE THREAD

**Issue by brandbrilliance** [menatwork-ia/valumsFileUploader#43]
This happens on 2.11.1 when you click on the pop-up window. I'm using version valumsFileUploader    3.1.0 rc2    build 16

You can still upload, but it doesn't work, as the file isn't there. When you upload via the normal file manager, it works 100%.

![Double File Upload](http://www.thyon.com/tl_files/content/lab/dev/github/images/valums-double-popup.jpg)

**Comment by andreasisaak** [comment]
Thanks for the report, duplicate to ticket #19
We are working on the solution.

**Comment by brandbrilliance** [comment]
Well since that's in German, I was unable to determine if this was an already reported issue (there are quite a lot of german tickets, making Contao's progress slow and duplicate).

**Comment by andreasisaak** [comment]
Thats the reason why i post the ticket no #19
Its not my cms ;) and i have no reason to stop all the german supporters to post german tickets (my english is very bad too)

You can see the solution on the following commit:

0987b7b85e1cca17062084c3c7bb0f67f98e3d15
