### ISSUE TITLE
Call to undefined function apache_request_headers()

### ISSUE THREAD

**Issue by tristanlins** [menatwork-ia/valumsFileUploader#44]
Auf unserem Server erhalte ich in der neuen Version die Meldung

```
Call to undefined function apache_request_headers() in
/var/www/clients/client30/web114/web/system/modules/valumsFileUploader/valumsFile.php
on line 100
```

Laut [Doku](http://php.net/manual/de/function.apache-request-headers.php) ist diese Funktion unter PHP <=5.3 nur verfügbar, wenn PHP als Modul ausgeführt wird, aber nicht via FastCGI.

```
Changelog
5.4.0    Diese Funktion wurde unter FastCGI verfügbar. Vorher wurde sie nur unterstützt, wenn PHP als Apache Modul installiert war.
```

**Comment by andreasisaak** [comment]
Danke für den Hinweis. Dann wäre es am besten zu prüfen ob die Funktion existiert und ansonsten eine eigene Funktion durchlaufen zu lassen.

http://www.php.net/manual/de/function.apache-request-headers.php#70810

**Comment by andreasisaak** [comment]
Diese Funktion verwenden wir laut meines Kollegen schon seit zig Commits nicht mehr. Und auch im ER war der Bug vor minimal 2-3 Versionen. Sicher das es die aktuellste vfu Version ist??

**Comment by tristanlins** [comment]
Ich hatte dir im IRC doch schon gesagt, das ein Update das Problem gelöst hat :-)

**Comment by andreasisaak** [comment]
Ich merke mir nicht alles ;)
