### ISSUE TITLE
[Contao 2.9] Could not load class FileUpload

### ISSUE THREAD

**Issue by math-GH** [menatwork-ia/valumsFileUploader#46]
Contao: 2.9.5
valumsFileUploader: 3.1.0 rc3

Tritt auf beim öffnen wollen des Uploadfensters (Dateiverwaltung -> Datei-Upload -> klick auf den Upload-Ordner)

``` php
Fatal error: Could not load class FileUpload in /var/www/.../system/functions.php on line 76

#0 /var/www/.../system/functions.php(76): __error(256, 'Could not load ...', '/var/www/...', 76, Array)
#1 /var/www/.../system/drivers/DC_Upload.php(68): __autoload('Could not load ...', 256)
#2 /var/www/.../system/modules/backend/Backend.php(234): DC_Upload->move('FileUpload')
#3 /var/www/.../contao/main.php(101): Backend->getBackendModule()
#4 /var/www/.../contao/main.php(304): Main->run('files')
#5 {main}
```

P.S. Es ist mein erstes github-Ticket. Ich hoffe, dass es hier richtig ist. Mal schaun wie die Formatierung hier zu stande kommt.

**Comment by andreasisaak** [comment]
Hallo erstmal,

um was für ein System handelt es sich?
Ich brauche ein paar Daten zum Server, sonst kann ich nicht helfen.

Und sag mir bitte nicht das es sich um einen Windows-Server handelt :(

**Comment by math-GH** [comment]
Nein nein, kein Windows-Server.

welche Infos brauchst du genau?

phpinfo (Auszug):

PHP Version 5.2.17-0.dotdeb.0
System  Linux Build Date    Aug 1 2011 15:11:40 
mysql Client API version    5.0.84

**Comment by andreasisaak** [comment]
Und auf welchem Server genau liegt das ganze? Ist es eine Debian Kiste? Ist es ein Qnap? etc etc.

**Comment by math-GH** [comment]
Hoster: Alfahosting
System: Linux alfa30XX 2.6.32-bpo.5-amd64 #1 SMP Wed Jul 20 09:10:04 UTC 2011 x86_64

**Comment by andreasisaak** [comment]
Dann kann ich mir das nur noch mit 2.9.x erklären. Kannst du nicht auf 2.10 aktualisieren?

**Comment by math-GH** [comment]
ich habe dir eben meine komplette phpinfo per Mail geschickt.

Ich habe kein Problem, wenn 2.9 nicht unterstützt wird. Ich hatte es mir eigentlich nur zum ausprobieren installiert und die Probleme festgestellt.

Ein Update auf >2.9 ist mir noch nicht möglich (Zeit und ein paar Erweiterungen)

**Comment by andreasisaak** [comment]
Wir haben grade keine Zeit für Tests an 2.9.5, ich achte beim nächsten Mal darauf die Version erst ab 2.10.x freizugeben.
