### ISSUE TITLE
Upload fails with mod_security

### ISSUE THREAD

**Issue by Toflar** [menatwork-ia/valumsFileUploader#48]
Hey Leute

Ich hab grad eine mögliche Ursache für einige Issues im Zusammenhang mit dem valumsFileUploader gefunden.
Bei einer Installation funktioniert der Uploader nur mit kleinen Dateien und unregelmässig, wenn mod_security aktiv ist.
Wenn ich allerdings

```
<IfModule mod_security.c>
    SecFilterEngine Off
    SecFilterScanPOST Off
</IfModule>
```

in die .htaccess einfüge, funktioniert alles reibungslos. Auch mit 70 MB Dateien etc.
Nun, das komplette deaktivieren der Firewall kann wahrscheinlich nicht die langfristige Lösung sein, aber ich hab weder die Möglichkeit, eine solche Umgebung nachzustellen, noch das notwendige Wissen über mod_security, um irgendwie zu testen, an was das liegen könnte.

Da müsste man sich wahrscheinlich mal mit einem Sysadmin zusammensetzen und das Problem zurückverfolgen. Evtl. ist es ja lösbar :-)

**Comment by kahl-dev** [comment]
@Toflar Hi ich habe mich mal heute ran gesetzt und wollte den Bug beheben. Hat ein wenig gedauert, bis ich das Szenario reproduzieren konnte. Ich hab nun ein aktuelles Debian mit mod_security am laufen. Aber das ist das Paket 2 (mod_security2.c). Wenn ich nun deinen Snippet nehme wird der Download dennoch abgebrochen. Auch wenn ich &lt;IfModule mod_security2.c&gt; zur Abfrage des Moduls benutze. Jede Abfrage in der htaccess wird einfach ignoriert. Den einzigen Erfolg konnte ich durch das direkte Editieren der Apache config oder der Virtual Hosts erreichen. Könntest du mir vielleicht sagen was für ein System und welches mod_security Package ihr am laufen habt.

**Comment by Toflar** [comment]
Hey @patrickkahl - Danke für deinen Einsatz!
Ich hab an der Konferenz mit Tristan und Andreas darüber gesprochen. Tristan meinte, dass mod_security der grösste Schmarrn ist, den er je gesehen hat und Andreas und ich hatten uns dann eigentlich darauf geeinigt, dass der valumsFileUploader mit aktivem mod_security einfach nicht funktioniert. Das kann man gut in die Installationsanleitung hauen :-)

**Comment by andreasisaak** [comment]
@patrickkahl 

Dann lass doch einfach die Abfrage drin und aktualisiere vielleicht noch die Doku der readme.md und das Wiki. Dann weiß hoffentlich auch bald jeder Bescheid ;)

**Comment by andreasisaak** [comment]
a56903c85090d67d5366d5f6385ba4a44bf847c9
